spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GH_CLIENT_ID}
            clientSecret: ${GH_CLIENT_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
              
          google:
            cilent_id: ${GG_CLIENT_ID}
            client-secret: ${GG_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            token-uri: https://oauth2.googleapis.com/token
            resource-uri: https://www.googleapis.com/oauth2/v2/userinfo
            scope:
              - email
              - profile
              
    provider:
      github:
        authorization-uri: https://github.com/login/oauth/authorize
        token-uri: https://github.com/login/oauth/access_token
        user-info-uri: https://api.github.com/user
        
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/blog
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        
server:
  servlet:
    session:
      timeout: 600
      
springboot:
  jwt:
    secret: somename!@#